# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable

ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

GOROBOTS    = ../../../..
LPZROBOTS   = $(ODEROBOTSSRCPREFIX)/../..
DUNGBOT		= $(GOROBOTS)/utils/sim_robots/dungbot
CONTROLLER  = $(GOROBOTS)/controllers/dungbot/walknet_rolling_ball


FILES      += main \
		DungBotEmptyController \
		DungBotSimulation      \
		$(CONTROLLER)/kinematicsController \
		$(CONTROLLER)/walknetcontroller \
		$(CONTROLLER)/walknetSeparateLeg \
		$(DUNGBOT)/dungbot_rolling_ball\

		

INC	  	   += -I. -I$(DUNGBOT) -I$(CONTROLLER)

LIBS       = -lreadline  -lncurses
