#ifndef __GOROBOTS_EDU_PROJECTS_TRIBOT_ACTION_H
#define __GOROBOTS_EDU_PROJECTS_TRIBOT_ACTION_H

enum Action {
  LEFT,
  RIGHT,
  FORWARD,
  BACKWARDS
};

#endif // end of __GOROBOTS_EDU_PROJECTS_TRIBOT_ACTION_H
