# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed

INCLUDE     = ../include
LPZROBOTS   = $(shell selforg-config $(CFGOPTS) --srcprefix)/..
AMOSIICONT  = $(INCLUDE)/controllers
UTILS       = $(INCLUDE)/utils
AMOSIIREAL  = $(LPZROBOTS)/real_robots/robots/amosii
USELASERSCANNER = $(shell ode_robots-config --uselaser)


FILES      += main \
 			 $(AMOSIIREAL)/cmdline \
 			 $(AMOSIIREAL)/console \
 			 $(AMOSIIREAL)/amosIIserialv1 \
 			 $(AMOSIIREAL)/amosIIserialv2 \
			 $(UTILS)/ann-framework/ann \
			 $(UTILS)/ann-framework/neuron \
			 $(UTILS)/ann-framework/synapse \
			 $(AMOSIICONT)/amosIIcontrol \
			 $(AMOSIICONT)/NeuralPreprocessingLearning \
			 $(AMOSIICONT)/NeuralLocomotionControlAdaptiveClimbing \
			 $(AMOSIICONT)/ModularNeuralControl \
			 $(AMOSIICONT)/BackboneJointControl \
			 $(UTILS)/interpolator2d \
			 $(UTILS)/ann-library/so2cpg \
			 $(UTILS)/ann-library/pcpg \
			 $(UTILS)/ann-library/psn \
			 $(UTILS)/ann-library/vrn \
			 $(UTILS)/ann-library/pmn \
			 $(UTILS)/ann-library/extendedso2cpg \
			 $(UTILS)/ann-library/adaptiveso2cpgsynplas \
			 $(AMOSIICONT)/delayline \
			 $(AMOSIICONT)/forwardmodel \
			 $(AMOSIICONT)/motormapping

INC        += -I$(INCLUDE)
INC        += -I$(AMOSIIREAL)

LIBS       += -lreadline  -lncurses

ifeq ($(USELASERSCANNER),1)
	INC      += -I/usr/local/include/urg -I$(LPZROBOTS)/real_robots
	LIBS     += -lurg_monitor -lurg -lurg_coordinate -lurg_geometry -lurg_connection -lurg_connection_sdl -lurg_common -lurg_system
	CPPFLAGS += -D LASERSCANNER
	FILES    += $(LPZROBOTS)/real_robots/sensors/laserscanner/laserScanner 
endif
