# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed


ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

BASSELDIR   = ../../..
LPZROBOTS   = $(ODEROBOTSSRCPREFIX)/..
AMOSIIUTIL  = $(BASSELDIR)/libs
AMOSIICONT  = ../controller

FILES      += main \
		     relativepositionsensor \
             fourwheeledrpos \
			 $(AMOSIICONT)/acicoRCcontroller \
			 $(AMOSIIUTIL)/rbf_network/ngnet\
			 $(AMOSIICONT)/RobotState
			 
			 
#ODEROBOTS  = $(LPZROBOTS)/ode_robots
#SELFORG    = $(LPZROBOTS)/selforg

INC        += -I$(AMOSIICONT)
INC        += -I$(AMOSIIUTIL)

LIBS       = -lreadline  -lncurses



