# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed

INCLUDE     = ../include
LPZROBOTS   = $(shell ode_robots-config $(CFGOPTS) --srcprefix)/..
AMOSIICONT  = $(INCLUDE)/controllers/
AMOSIIUTIL  = $(INCLUDE)/utils

FILES      += main \
			 $(AMOSIIUTIL)/ann-framework/ann \
			 $(AMOSIIUTIL)/ann-framework/neuron \
			 $(AMOSIIUTIL)/ann-framework/synapse \
			 $(AMOSIICONT)/amosIIcontrol \
			 $(AMOSIICONT)/NeuralPreprocessingLearning \
			 $(AMOSIICONT)/NeuralLocomotionControlAdaptiveClimbing \
			 $(AMOSIICONT)/ModularNeuralControl \
			 $(AMOSIICONT)/BackboneJointControl \
			 $(AMOSIIUTIL)/interpolator2d \
			 $(AMOSIIUTIL)/ann-library/so2cpg \
			 $(AMOSIIUTIL)/ann-library/pcpg \
			 $(AMOSIIUTIL)/ann-library/psn \
			 $(AMOSIIUTIL)/ann-library/vrn \
			 $(AMOSIIUTIL)/ann-library/pmn \
			 $(AMOSIIUTIL)/ann-library/extendedso2cpg \
			 $(AMOSIIUTIL)/ann-library/adaptiveso2cpgsynplas \
			 $(AMOSIICONT)/delayline \
			 $(AMOSIICONT)/forwardmodel \
			 $(AMOSIICONT)/motormapping

INC        += -I$(INCLUDE)

LIBS       = -lreadline  -lncurses





