# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed


ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

MAINDIR   = ../../..
NIMMFILE  = $(MAINDIR)/utils/sim_robots/nimm4ii_v2
LPZROBOTS   = $(ODEROBOTSSRCPREFIX)/..
AMOSIIUTIL  = $(MAINDIR)/utils
AMOSIICONT  = $(MAINDIR)/controllers/nimm4ii/reinforcement_learning_control

FILES      += main \
             		 $(NIMMFILE)/fourwheeledrpos \
             		 $(NIMMFILE)/relativepositionsensor \
			 $(AMOSIICONT)/NimmExp2 \
			 $(AMOSIIUTIL)/rbf-framework/ngnet\
			 $(AMOSIICONT)/NimmExp2RobotState
			 
			 
#ODEROBOTS  = $(LPZROBOTS)/ode_robots
#SELFORG    = $(LPZROBOTS)/selforg

INC        += -I$(AMOSIICONT)
INC        += -I$(MAINDIR)
INC        += -I$(NIMMFILE)

LIBS       = -lreadline  -lncurses



