# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed


ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

GOROBOTS     = ../../..
LPZROBOTS    = $(ODEROBOTSSRCPREFIX)/..
UTILS        = $(GOROBOTS)/utils
NIMM4IICONT  = $(GOROBOTS)/controllers/nimm4ii

FILES      += main \
             fourwheeledrpos \
             $(UTILS)/esn-framework/networkmatrix \
             $(NIMM4IICONT)/acicorcactorcontroller \
             $(NIMM4IICONT)/ngnet


#ODEROBOTS  = $(LPZROBOTS)/ode_robots
#SELFORG    = $(LPZROBOTS)/selforg

INC        += -I$(GOROBOTS)

LIBS       = -lreadline  -lncurses



