# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed


ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

GOROBOTS     = ../../..
NIMMFILE  = $(GOROBOTS)/utils/sim_robots/nimm4ii_v1
LPZROBOTS    = $(ODEROBOTSSRCPREFIX)/..
UTILS        = $(GOROBOTS)/utils
NIMM4IICONT  = $(GOROBOTS)/controllers/nimm4ii

FILES      += main \
              $(NIMMFILE)/fourwheeledrpos \
                         $(NIMMFILE)/relativepositionsensor \
             $(UTILS)/esn-framework/networkmatrix \
             $(NIMM4IICONT)/acicorcactorcontroller \
             $(NIMM4IICONT)/ngnet


#ODEROBOTS  = $(LPZROBOTS)/ode_robots
#SELFORG    = $(LPZROBOTS)/selforg

INC        += -I$(GOROBOTS)
INC        += -I$(NIMM4IICONT)
INC        += -I$(NIMMFILE)



LIBS       = -lreadline  -lncurses
# add this to avoid problem for 64 bit PC
LIBS = -Wl,--no-as-needed -lgsl -lgslcblas -lm



