# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation to the FILES
#   variable
# You can also tell where you have lpzrobots installed

SRCDIR      = src/

MYFILES	   += main EMGapproxRBF DelimitedFileReader SimpleRNG rbf_network


FILES      += $(addprefix $(SRCDIR), $(MYFILES))

INC        += -I$(GOROBOTS)

# add this to avoid problem for 64 bit PC
LIBS = -Wl,--no-as-needed -lgsl -lgslcblas -lm -lreadline  -lncurses
