#LIBSELFORG=$(shell selforg-config $(CFGOPTS) --libfile)
#LIBSELFORGSHARED:=$(shell selforg-config $(CFGOPTS) --solibfile)
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

#LIBODEROBOTS=$(shell ode_robots-config $(CFGOPTS) --libfile)
#LIBODEROBOTSSHARED:=$(shell ode_robots-config $(CFGOPTS) --solibfile)
ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory

GOROBOTS    = ../..
LPZROBOTS	= $(ODEROBOTSSRCPREFIX)/..
#AMOSIICONT  = $(GOROBOTS)/controller/amosII/6CPGsControlwithLearning
#AMOSIICONT  = $(GOROBOTS)/controller/amosII/TryMentoCarlo


FILES      += main \
			  amosIIcontrol \
			  NeuralPreprocessingReflex \
			  NeuralLearningAndMemoryYourExtension \
			  NeuralLocomotionControlAdaptiveClimbing \
			  ChaoscontrAndPostproc

#INC        += -I$(GOROBOTS)/controller/amosII/6CPGsControlwithLearning
INC        += -I
LIBS       = -lreadline  -lncurses		