# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed

ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

GOROBOTS    = ../../../..
LPZROBOTS   = $(ODEROBOTSSRCPREFIX)/..
AMOSIICONT  = $(GOROBOTS)/controllers/amosii/modular_neural_control_hormone
AMOSIIUTIL  = $(GOROBOTS)/utils
AMOSIIREAL  = $(LPZROBOTS)/real_robots/robots/amosii

FILES      += main \
 			 $(AMOSIIREAL)/cmdline \
 			 $(AMOSIIREAL)/console \
 			 $(AMOSIIREAL)/amosIIserialv1 \
 			 $(AMOSIIREAL)/amosIIserialv2 \
			 $(AMOSIIUTIL)/ann-framework/ann \
			 $(AMOSIIUTIL)/ann-framework/neuron \
			 $(AMOSIIUTIL)/ann-framework/synapse \
			 $(AMOSIIUTIL)/hormone-framework/hormone \
			 $(AMOSIICONT)/amosIIcontrol \
			 $(AMOSIICONT)/hormone_control \
			 $(AMOSIICONT)/NeuralPreprocessingLearning \
			 $(AMOSIICONT)/NeuralLocomotionControlAdaptiveClimbing \
			 $(AMOSIICONT)/ModularNeuralControl \
			 $(AMOSIICONT)/MuscleModel \
			 $(AMOSIICONT)/BackboneJointControl \
			 $(AMOSIIUTIL)/interpolator2d \
			 $(AMOSIIUTIL)/ann-library/so2cpg \
			 $(AMOSIIUTIL)/ann-library/pcpg \
			 $(AMOSIIUTIL)/ann-library/psn \
			 $(AMOSIIUTIL)/ann-library/vrn \
			 $(AMOSIIUTIL)/ann-library/pmn \
			 $(AMOSIIUTIL)/ann-library/extendedso2cpg \
			 $(AMOSIIUTIL)/ann-library/adaptiveso2cpgsynplas \
			 $(AMOSIICONT)/delayline \
			 $(AMOSIICONT)/forwardmodel \
			 $(AMOSIICONT)/motormapping

INC        += -I$(GOROBOTS)
INC        += -I$(AMOSIIREAL)

LIBS       = -lreadline  -lncurses





