
# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed

ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

GOROBOTS    = ../../../..
LPZROBOTS   = $(ODEROBOTSSRCPREFIX)/..
DUNGCONT  = $(GOROBOTS)/controllers/dungbeetle/modular_neural_control/dung_beetle
MODULARCONT  = $(GOROBOTS)/controllers/dungbeetle/modular_neural_control/
AMOSIIUTIL  = $(GOROBOTS)/utils

FILES      += main \
			 $(DUNGCONT)/dungBeetlecontrol\
			 $(MODULARCONT)/plastic \
			 $(AMOSIIUTIL)/ann-framework/ann\
			 $(AMOSIIUTIL)/ann-framework/neuron \
			 $(AMOSIIUTIL)/ann-framework/synapse \
			 $(AMOSIIUTIL)/interpolator2d \
			 $(AMOSIIUTIL)/ann-library/so2cpg \
			 $(AMOSIIUTIL)/ann-library/pcpg \
			 $(AMOSIIUTIL)/ann-library/psn \
			 $(AMOSIIUTIL)/ann-library/vrn \
			 $(AMOSIIUTIL)/ann-library/pmn \
			 $(AMOSIIUTIL)/ann-library/extendedso2cpg \
			 $(AMOSIIUTIL)/ann-library/adaptiveso2cpgsynplas \
			

INC        += -I$(GOROBOTS)

LIBS       = -lreadline  -lncurses





