# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed
# $(GOROBOTS)/projects/dungbeetle/adaptivecpg/sim/amosII

 
ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

GOROBOTS    = ../../../..
LPZROBOTS   = $(ODEROBOTSSRCPREFIX)/..
AMOSIICONT  = $(GOROBOTS)/controllers/dungbeetle/modular_neural_control
AMOSIIUTIL  = $(GOROBOTS)/utils

FILES      += main \
			 $(AMOSIIUTIL)/ann-framework/ann\
			 $(AMOSIIUTIL)/ann-framework/neuron \
			 $(AMOSIIUTIL)/ann-framework/synapse \
			 $(AMOSIICONT)/amosIIcontrol \
			 $(AMOSIICONT)/NeuralPreprocessingLearning \
			 $(AMOSIICONT)/NeuralLocomotionControlAdaptiveClimbing \
			 $(AMOSIICONT)/ModularNeuralControl \
			 $(AMOSIICONT)/MuscleModel \
			 $(AMOSIICONT)/BackboneJointControl \
			 $(AMOSIICONT)/plastic \
			 $(AMOSIIUTIL)/interpolator2d \
			 $(AMOSIIUTIL)/ann-library/so2cpg \
			 $(AMOSIIUTIL)/ann-library/pcpg \
			 $(AMOSIIUTIL)/ann-library/psn \
			 $(AMOSIIUTIL)/ann-library/vrn \
			 $(AMOSIIUTIL)/ann-library/pmn \
			 $(AMOSIIUTIL)/ann-library/extendedso2cpg \
			 $(AMOSIIUTIL)/ann-library/adaptiveso2cpgsynplas \
			 $(AMOSIICONT)/delayline \
			 $(AMOSIICONT)/forwardmodel \
			 $(AMOSIICONT)/motormapping \
			 $(GOROBOTS)/projects/dungbeetle/manipulation_control/sim/dungbeetle
			 

INC        += -I$(GOROBOTS)

LIBS       = -lreadline  -lncurses





