# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed

GOROBOTS    = ../../../..
UTILS       = $(GOROBOTS)/utils
CONTROLLERS = $(GOROBOTS)/controllers/nejihebi
ANN_FRM     = $(UTILS)/ann-framework
ANN_LIB     = $(UTILS)/ann-library

FILES      += main \
              $(CONTROLLERS)/nejihebiinterface \
              $(CONTROLLERS)/nejihebilpzinterface \
              $(CONTROLLERS)/nejihebicontrollerbase \
              $(CONTROLLERS)/nejihebipi2controller \
              $(CONTROLLERS)/PI2Wholesteps \
              $(CONTROLLERS)/KinemodelController \
              $(CONTROLLERS)/GenerateNoise \

INC        += -I$(GOROBOTS) 