# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed
#FILES      += main amosII\
#ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory
#SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory


INCLUDE     = ../include
#LPZROBOTS	= $(shell ode_robots-cosnfig $(CFGOPTS) --srcprefix)/..
AMOSIICONT  = $(INCLUDE)/controllers


FILES      += main \
              $(AMOSIICONT)/amosIIcontrol \
              $(AMOSIICONT)/NeuralPreprocessingReflex \
              $(AMOSIICONT)/NeuralLearningAndMemoryYourExtension \
              $(AMOSIICONT)/NeuralLocomotionControlAdaptiveClimbing \
              $(AMOSIICONT)/ChaoscontrAndPostproc \
              $(AMOSIICONT)/KineController 

INC        += -I$(INCLUDE)

LIBS       = -lreadline  -lncurses



