# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable

ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

GOROBOTS    = ../../..
LPZROBOTS   = $(ODEROBOTSSRCPREFIX)/..


FILES      += main \

INC	  += -I

LIBS       = -lreadline  -lncurses
