# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed


ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

MAINDIR   = ../../..
NIMMFILE  = ..
LPZROBOTS   = $(ODEROBOTSSRCPREFIX)/..
AMOSIIUTIL  = $(MAINDIR)/utils
AMOSIICONT  = $(MAINDIR)/controllers/nimm4ii/action_sequence_learning

FILES      += main \
                         $(NIMMFILE)/fourwheeledrpos_gripper \
                         $(NIMMFILE)/relativepositionsensor \
			 $(AMOSIICONT)/NimmComplexASL \
			 $(AMOSIIUTIL)/rbf-framework/ngnet\
			 $(AMOSIICONT)/NimmComplexRobotStateASL
			 
			 
#ODEROBOTS  = $(LPZROBOTS)/ode_robots
#SELFORG    = $(LPZROBOTS)/selforg

INC        += -I$(AMOSIICONT)
INC        += -I$(MAINDIR)
INC        += -I$(NIMMFILE)

LIBS       = -lreadline  -lncurses



