# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed

ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

GOROBOTS = ../../..
NIMMFILE  = $(GOROBOTS)/utils/sim_robots/nimm4ii_v2
UTILS        = $(GOROBOTS)/utils
NIMM4IICONT  = $(GOROBOTS)/controllers/nimm4ii

FILES      = main \
              $(NIMM4IICONT)/action_sequence_learning/aslcontroller \
              $(NIMM4IICONT)/action_sequence_learning/aslt \
              $(NIMMFILE)/fourwheeledrpos_gripper \
              $(NIMMFILE)/relativepositionsensor \
              $(GOROBOTS)/utils/ann-framework/ann \
              $(GOROBOTS)/utils/ann-framework/neuron \
              $(GOROBOTS)/utils/ann-framework/backpropagation \
			  $(GOROBOTS)/utils/ann-framework/synapse 

INC        += -I$(GOROBOTS)
INC        += -I$(NIMM4IICONT)
INC        += -I$(NIMMFILE)

# add this to avoid problem for 64 bit PC
LIBS = -Wl,--no-as-needed -lgsl -lgslcblas -lm
