# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
# to the FILES variable
# You can also tell where you haved lpzrobots installed

FILES = main networkmatrix newACICO ngnet nimm4_doublePole

# add this to avoid problem for 64 bit PC
LIBS = -Wl,--no-as-needed -lgsl -lgslcblas -lm

