# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
# to the FILES variable
# You can also tell where you haved lpzrobots installed

ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix) #ode_robots directory
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

GOROBOTS    = ../../../..
LPZROBOTS   = $(ODEROBOTSSRCPREFIX)/..

FILES = main networkmatrix newACICO ngnet nimm4_doublePole
