# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed

# FILES      = main amosIIcontrol ChaoscontrAndPostproc NeuralLearningAndMemoryYourExtension NeuralLocomotionControlAdaptiveClimbing NeuralPreprocessingReflex


# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed


ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory


GOROBOTS    = ../../../..
LPZROBOTS	= $(ODEROBOTSSRCPREFIX)/..
AMOSIICONT  = $(GOROBOTS)/controller/amosii/ren_4cpgcontrol_goal




FILES      += main \
			  $(AMOSIICONT)/amosIIcontrol \
			  $(AMOSIICONT)/NeuralPreprocessingReflex \
			  $(AMOSIICONT)/NeuralLearningAndMemoryYourExtension \
			  $(AMOSIICONT)/NeuralLocomotionControlAdaptiveClimbing \
			  $(AMOSIICONT)/ChaoscontrAndPostproc
			  
              #amosIIcontrol \
			  #NeuralPreprocessingReflex \
			  #NeuralLearningAndMemoryYourExtension \
			  #NeuralLocomotionControlAdaptiveClimbing \
			  #ChaoscontrAndPostproc\
		
INC        += -I $(GOROBOTS)/controller/amosii/ren_4cpgcontrol_goal


LIBS       = -lreadline  -lncurses		
		
	