# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed

GOROBOTS    = ../../..
UTILS       = $(GOROBOTS)/controller/utils
NEJIHEBI    = $(GOROBOTS)/controller/nejihebi
ANN_FRM     = $(UTILS)/ann-framework
ANN_LIB     = $(UTILS)/ann-library

FILES      += main \
              $(NEJIHEBI)/nejihebiinterface \
              $(NEJIHEBI)/nejihebilpzinterface \
              $(NEJIHEBI)/nejihebicontrollerbase \
              nejihebicontroller

INC        += -I$(GOROBOTS)/controller/