# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed

#LIBSELFORG=$(shell selforg-config $(CFGOPTS) --libfile)
#LIBSELFORGSHARED:=$(shell selforg-config $(CFGOPTS) --solibfile)
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

#LIBODEROBOTS=$(shell ode_robots-config $(CFGOPTS) --libfile)
#LIBODEROBOTSSHARED:=$(shell ode_robots-config $(CFGOPTS) --solibfile)
ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory

GOROBOTS    = ../../../..
LPZROBOTS	= $(ODEROBOTSSRCPREFIX)/..
AMOSIICONT  = $(GOROBOTS)/controller/amosii/modular_neural_control
AMOSIIREAL   = $(LPZROBOTS)/real_robots/robots/amosii
AMOSIIUTIL  = $(GOROBOTS)/controller/utils


FILES      += main \
			  $(AMOSIIUTIL)/ann-framework/ann \
              $(AMOSIIUTIL)/ann-framework/neuron \
              $(AMOSIIUTIL)/ann-framework/synapse \
 			  $(AMOSIIREAL)/cmdline \
 			  $(AMOSIIREAL)/console \
 			  $(AMOSIIREAL)/amosIIserialv1 \
 			  $(AMOSIIREAL)/amosIIserialv2 \
			  $(AMOSIICONT)/amosIIcontrol \
			  $(AMOSIICONT)/NeuralPreprocessingLearning \
			  $(AMOSIICONT)/NeuralLocomotionControlAdaptiveClimbing \
			  $(AMOSIICONT)/ModularNeuralControl \
			  $(AMOSIICONT)/BackboneJointControl \
			  $(AMOSIIUTIL)/interpolator2d \
			  $(AMOSIIUTIL)/ann-library/combination \
			  $(AMOSIIUTIL)/ann-library/so2cpg \
			  $(AMOSIIUTIL)/ann-library/pcpg \
			  $(AMOSIIUTIL)/ann-library/psn \
			  $(AMOSIIUTIL)/ann-library/vrn \
			  $(AMOSIIUTIL)/ann-library/pmn \
			  $(AMOSIIUTIL)/ann-library/extendedso2cpg \
              $(AMOSIIUTIL)/ann-library/adaptiveso2cpgsynplas \
			  $(AMOSIICONT)/delayline \
			  $(AMOSIICONT)/forwardmodel \
			  $(AMOSIICONT)/motormapping

INC        += -I$(GOROBOTS)/controller/amosii
INC        += -I$(AMOSIIREAL)

LIBS       = -lreadline  -lncurses




