# Configuration for simulation makefile
# Please add all cpp files you want to compile for this simulation
#  to the FILES variable
# You can also tell where you haved lpzrobots installed


GOROBOTS    = ../../../
LPZROBOTS   =$(ODEROBOTSSRCPREFIX)/..
MILLIPEDECONT  = $(GOROBOTS)/controllers/millipede/centralized_cpg
MILLIPEDESIM  = $(GOROBOTS)/utils/sim_robots/millipede
MILLIPEDEUTIL     = $(GOROBOTS)/utils
LPZLIBS = $(GOROBOTS)/../lpzrobots/ode_robots/include/ode_robots


FILES      += main \
 			 $(MILLIPEDESIM)/millipede \
			 $(MILLIPEDECONT)/centralized_cpg \
			

INC        += -I$(GOROBOTS)
INC        += -I$(MILLIPEDESIM)
INC		   += -I$(MILLIPEDECONT)

LIBS       = -lreadline  -lncurses





