
#FILES      += main


#LIBSELFORG=$(shell selforg-config $(CFGOPTS) --libfile)
#LIBSELFORGSHARED:=$(shell selforg-config $(CFGOPTS) --solibfile)
SELFORGSRCPREFIX=$(shell selforg-config $(CFGOPTS) --srcprefix)  #selforg directory

#LIBODEROBOTS=$(shell ode_robots-config $(CFGOPTS) --libfile)
#LIBODEROBOTSSHARED:=$(shell ode_robots-config $(CFGOPTS) --solibfile)
ODEROBOTSSRCPREFIX=$(shell ode_robots-config $(CFGOPTS) --srcprefix)  #ode_robots directory

GOROBOTS    = ../../../..
LPZROBOTS	= $(ODEROBOTSSRCPREFIX)/..
#AMOSIICONT  = .    #$(GOROBOTS)/controller/amosII/6CPGsControlwithLearning
ROBOTDIR     = $(GOROBOTS)/utils/sim_robots
CONTROLS    = $(GOROBOTS)/controllers/tribot/cooperation_control/

FILES      += $(GOROBOTS)/utils/real_robots/sensors/lizard_ear/lizard_ear\
              $(basename $(shell find $(CONTROLS) -name '*.cpp'))\
              $(ROBOTDIR)/tribot/tribot\
              $(basename $(shell find $(SOURCEDIR) -name '*.cpp'))\
              #$(ROBOTDIR)/sensors/lizardear\

INC        += -I$(ROBOTDIR)/tribot\
              -I$(GOROBOTS)/utils/real_robots/sensors/lizard_ear\
              -I$(CONTROLS)\
              #-I$(ROBOTDIR)/sensors\

LIBS       = -lreadline  -lncurses

# Can be used to print out any variable by "make print-VARIABLE"
print-%  : ; @echo $* = $($*)
